# Generated by Django 4.1.7 on 2023-03-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='mostra',
            field=models.BooleanField(default=True),
        ),
    ]
